
apiVersion: apps/v1
kind: Deployment
metadata:
  name: transaction
spec:
  replicas: 2
  selector:
    matchLabels:
      app: transaction
  template:
    metadata:
      labels:
        app: transaction
    spec:
      containers:
        - name: transaction
          image: transaction:latest
          ports:
            - containerPort: 3002
          env:
            - name: MONGO_URL
              value: mongodb://mongo/transaction
  