
apiVersion: apps/v1
kind: Deployment
metadata:
  name: blockchain
spec:
  replicas: 2
  selector:
    matchLabels:
      app: blockchain
  template:
    metadata:
      labels:
        app: blockchain
    spec:
      containers:
        - name: blockchain
          image: blockchain:latest
          ports:
            - containerPort: 3004
          env:
            - name: MONGO_URL
              value: mongodb://mongo/blockchain
  